# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='language_disabilities',
            new_name='LanguageDisabilities',
        ),
        migrations.RenameModel(
            old_name='mathematical_disabilities',
            new_name='MathematicalDisabilities',
        ),
        migrations.RenameModel(
            old_name='parent_awareness',
            new_name='ParentAwareness',
        ),
        migrations.RenameModel(
            old_name='Student_info',
            new_name='StudentInfo',
        ),
    ]
