# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170609_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='father_contact',
            field=models.CharField(max_length=10),
        ),
    ]
