# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170613_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='ParentAwarenessScore',
            new_name='ParentalMetricScore',
        ),
        migrations.DeleteModel(
            name='ParentAwareness',
        ),
        migrations.AlterField(
            model_name='parentalmetricscore',
            name='awareness_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ParentalMetric'),
        ),
    ]
