# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170613_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentalmetricscore',
            old_name='awareness_score',
            new_name='metric_score',
        ),
        migrations.RenameField(
            model_name='parentalmetricscore',
            old_name='awareness_type',
            new_name='metric_type',
        ),
    ]
