# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170613_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_contact',
            field=models.CharField(max_length=10),
        ),
    ]
